### ISSUE TITLE
Will build but can't login

### ISSUE THREAD

**Issue by patrickacollier** [jontitmus-code/SuiteCRM8_docker#1]
using Docker Desktop on windows. The containers will build and I can access localhost as well as phpadmin. After running the helper scripts I can see the database and users created. When trying to login, I get about 55seconds in and get a 500 service error. When I check the php logs it appears to be an issue with pdo_mysql not loading (or failing to). Have you experience this issue?

**Comment by jontitmus-code** [comment]
Hi @patrickacollier, 
Yes - this will be related to the `DATABASE_URL` environment variable. For whatever reason the environment variable created by the installer, (`.env.local`), created in the `www` folder is ignored in favour of Docker environment variables which you will find in the `environment` folder of the repo. So, if you've changed any of the database config, either the name of the container and therefore the `host`, the `username` or `password` of the db user, or even the `port` then you will need to update the connection string the `.env`, (currently called `sample.env`), file inline with any changes. Please let me know if this resolves the issue or if you haven't made any changes!

**Comment by jontitmus-code** [comment]
Hi @patrickacollier,
Any luck with this?

**Comment by patrickacollier** [comment]
I didn't have any luck. I left the default config in place. At this point i'm assuming its the luck of the draw in how the linux container is trying to install  pdo_mysql before msqlnd. On a clean run of composer I would get an error stating `pdo_mysql.so: undefined symbol: mysqlnd_allocator in Unknown on line 0`
I will try to get back around to debugging this, but just wanted to log the error. Running Docker Desktop on windows.

**Comment by jontitmus-code** [comment]
@patrickacollier, as a matter of interest, are you running Docker on WSL2 or Hyper-V? I have to admit that I only tested this on WSL2...

**Comment by patrickacollier** [comment]
WSL2

**Comment by wilj** [comment]
> I didn't have any luck. I left the default config in place. At this point i'm assuming its the luck of the draw in how the linux container is trying to install pdo_mysql before msqlnd. On a clean run of composer I would get an error stating `pdo_mysql.so: undefined symbol: mysqlnd_allocator in Unknown on line 0` I will try to get back around to debugging this, but just wanted to log the error. Running Docker Desktop on windows.

I get the same error message in the logs, but everything still works correctly.  I found it while troubleshooting another issue, which I managed to resolve, but I still see this error message once after startup, then everything works as expected afterwards.

**Comment by jontitmus-code** [comment]
Sorry, I'll be honest I hadn't had chance, (and unfortunately forgot), to look into this any further. Looking this afternoon, I had a not too dissimilar error relating to pdo_mysql. Having disabled the pdo_mysql extension in php.ini it has now disappeared. This may explain the error you're getting to @wilj as you didn't report any functional issues too. Ill push a change to reflect this up now. (Also added PHP error logging too).

**Comment by wilj** [comment]
Thank you!

Somewhat unrelated, but my fork has some extra automation for the installer, if you want to use any of it: [https://github.com/wilj/SuiteCRM8_docker/blob/master/suitecrm/docker/entrypoint.sh](https://github.com/wilj/SuiteCRM8_docker/blob/master/suitecrm/docker/entrypoint.sh)

I'd send a pull request, but I've made enough changes that it might be easier to just pick out the pieces you want.

**Comment by jontitmus-code** [comment]
@patrickacollier, are you still experiencing this issue or would it be fair to close this issue?
