### ISSUE TITLE
Upload File Size | error | Warning: Your PHP configuration should be changed to allow files of at least 6MB to be uploaded.

### ISSUE THREAD

**Issue by rithsila** [jontitmus-code/SuiteCRM8_docker#10]
![hD8E1aFmvw](https://user-images.githubusercontent.com/74228472/163553793-aea0a38a-96df-4938-9990-8d7be3b49b91.png)

**Comment by jontitmus-code** [comment]
@rithsila, based on your screenshot, I'm not quite sure what you are running here. But if you are spinning this up based on the complete repo, you'll find that this has already been accounted for: https://github.com/jontitmus-code/SuiteCRM8_docker/blob/a32fab9f6e43c496d9094fd3c96e1813e2c14d16/docker/config/php/php.ini#L855

**Comment by terencelhl** [comment]
Hi there, the php.ini loaded is located in /etc/php/7.4/cli folder . For fast resolution, we could copy the php.ini from apache2 into cli folder. cheers.
