### ISSUE TITLE
Cron

### ISSUE THREAD

**Issue by terencelhl** [jontitmus-code/SuiteCRM8_docker#11]
Hi Jon,

Saw there is cron file included. How can I deploy it to the container?

**Comment by terencelhl** [comment]
Alright, thanks for giving me a chance in contributing! Found the solution i.e. adding the below into Dockerfile, above EXPOSE 80.

COPY ./docker/config/cron/suitecrm /etc/cron.d/suitecrm
RUN chmod 0644 /etc/cron.d/suitecrm
RUN chown root: /etc/cron.d/suitecrm
RUN crontab /etc/cron.d/suitecrm
RUN touch /var/log/cron.log
RUN service cron start
CMD cron && tail -f /var/log/cron.log

**Comment by jontitmus-code** [comment]
Hey @terencelhl,
Sorry for the lack of response, I've been kind of off grid for a few days! I'm glad you found your solution though and thank you for sharing!
Jon
