### ISSUE TITLE
need help to INSTALL SuiteCRM8 ?

### ISSUE THREAD

**Issue by punkyard** [jontitmus-code/SuiteCRM8_docker#13]
STEPS TO INSTALL:

```
$ su dockeruser
$ cd
$ mkdir SuiteCRM
$ cd SuiteCRM
$ git clone https://github.com/jontitmus-code/SuiteCRM8_docker.git
$ cd SuiteCRM8_docker
$ docker-compose up -d
```

LET INSTALL FINISH, then:

```
$ docker exec -it suitecrm8_docker-suitecrm-1 /bin/bash
$ chmod +x /var/www/html/SuiteCRM/bin/console && \
/var/www/html/SuiteCRM/bin/console suitecrm:app:install -u "admin" -p "admin" -U "suitecrm" -P "suitecrm" -H "mysql_crm" -N "suitecrm" -S "http://localhost/" -d "yes"
```
> chmod: cannot access '/var/www/html/SuiteCRM/bin/console': No such file or directory

No file nor directory!?! (no /bin in /var/www/html/SuiteCRM)
What should be done from there, please?

**Comment by jontitmus-code** [comment]
Hi @punkyard,
Could you confirm that you've been following the instructions provided here please?
https://github.com/jontitmus-code/SuiteCRM8_docker/blob/master/README.md
Specifically point 4... If you haven't done this, it wont exist...

**Comment by punkyard** [comment]
well, I thought I did follow the instructions from 
https://github.com/jontitmus-code/SuiteCRM8_docker/blob/master/README.md
but i'm so opened to any advice 😅👍

**Comment by punkyard** [comment]
I put all my command steps up here.
Then I did something wrong: it needs the cloning (3) AND the zip file (4).. I think I didn't get that part.

So I should try:

1 & 2. INSTALL DOCKER and COMPOSE PLUGIN on ubuntu 22.04:
using a 'sudo' AND 'docker' user
```
$ sudo apt update
$ sudo apt-get install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release -y
$ sudo mkdir -m 0755 -p /etc/apt/keyrings
$ curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
$ echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
$(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
$ sudo apt update
$ sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin -y
$ sudo docker run hello-world
$ sudo systemctl enable --now docker
$ docker version
$ docker compose version
```

3. CLONE THE REPOSITORY into /root folder:
```
$ sudo git clone https://github.com/jontitmus-code/SuiteCRM8_docker.git /root/SuiteCRM/
```

4. DOWNLOAD SuiteCRM in /var/www/html/SuiteCRM:
```
$ sudo wget https://suitecrm.com/download/128/suite82/562059/suitecrm-8-2-4.zip /var/www/html
$ sudo unzip suitecrm-8-2-4.zip -d SuiteCRM
```

5 & 6. RUN DOCKER COMPOSE UP on .yml in /root folder
Apache server should already listening on port 80. Change the port in .yml file:
```
$ nano /root/SuiteCRM/docker-compose.yml
$ sudo docker compose -f /root/SuiteCRM/docker-compose.yml up -d
```

7. LET INSTALL FINISH, then:
```
$ docker exec -it suitecrm8_docker-suitecrm-1 /bin/bash
$ chmod +x /var/www/html/SuiteCRM/bin/console && \
/var/www/html/SuiteCRM/bin/console suitecrm:app:install -u "admin" -p "admin" -U "suitecrm" -P "suitecrm" -H "mysql_crm" -N "suitecrm" -S "http://localhost/" -d "yes"
```

What do you think @jontitmus-code?

**Comment by jontitmus-code** [comment]
Looks like you downloaded/unzipped the SuiteCRM files into the wrong place. The files, unless you've changed the compose file, should be unzipped into root/SuiteCRM/www/SuiteCRM

**Comment by jontitmus-code** [comment]
any luck @punkyard?

**Comment by jontitmus-code** [comment]
@punkyard, assuming this solved the issue? If I don't hear otherwise, I'll close the issue 😊

**Comment by punkyard** [comment]
hi @jontitmus-code, thanks for your concern.
Unfortunately I wasn't able to come back to it these days, facing another issue ..
If I can't come to back to this soon, I'll manage to let you know in another thread
Thanks, bye

**Comment by ViralAgency** [comment]
Hello, 

i' m installing this repo, and i understand where is the problem of @punkyard.

This solve the problem:

```
cd var/www/html
mv SuiteCRM-8.2.4 SuiteCRM
```

Wrong folder name due the original name of the unzipped folder.

**Comment by 2023Felix** [comment]
~ % git clone https://github.com/jontitmus-code/SuiteCRM8_docker.git
Cloning into 'SuiteCRM8_docker'...
fatal: unable to access 'https://github.com/jontitmus-code/SuiteCRM8_docker.git/': Failed to connect to github.com port 443 after 75011 ms: Couldn't connect to server

**Comment by jontitmus-code** [comment]
Closed due to age. Please raise another issue if anyone else is experiencing this issue! Many thanks/
