### ISSUE TITLE
setup issue

### ISSUE THREAD

**Issue by ccarabine** [jontitmus-code/SuiteCRM8_docker#14]
when i ran the suitecrm install.txt
i got 
upload file size error warning your php configuration should be changedd to allow files of at least 6mb

i went to http://localhost , it redirected me to install

put these details in 
url of suitcrm instance: http://localhost
suitecrm databaseuser:  suitcrm
user password : suitcrm
host name : localhost
databasename: mysql_crm
port 3306
admin name : admin
password : admin

tried a few different combinations and clicked proceed and got an empty pink dialog box

**Comment by jontitmus-code** [comment]
This has been corrected in this version to allow memory: 512M and file uploads of 10M
