### ISSUE TITLE
Not serving files, just listing them?

### ISSUE THREAD

**Issue by amks1** [jontitmus-code/SuiteCRM8_docker#17]
Hi, sorry I'm not that familiar with the php side of things. I followed all the instructions, unzipped the latest version `8.7.1` into `./www/SuiteCRM` folder, and ran `docker-compose up -d`. When I visit the IP:8080, what I get is:

![image](https://github.com/user-attachments/assets/8ac94dd1-3253-4836-a7ac-dd30ad511d54)

Any help would be great :)

**Comment by jontitmus-code** [comment]
Hi @amks1, 
I would hazard that this is a permissions issue. 
I've committed an update to the dockerfile which should resolve this issue. 
If you pull the changes and rebuild the image you should be good to go.
 
Let me know how it goes!

**Comment by amks1** [comment]
Unfortunately I get the same issue with the updated Dockerfile. :(
I did a docker system prune and rebuilt to be sure.

**Comment by jontitmus-code** [comment]
@amks1 , sorry to be a pain but could you let me know if your running on top of Windows (WSL2 or Hyper-V), OS X, or Linux please? It might also be worth re-running the new commands included in the dockerfile from within the container when it's running.

**Comment by amks1** [comment]
Did some tinkering and found the issue, fixed by pull request #18
