### ISSUE TITLE
Helper File might be incorrect

### ISSUE THREAD

**Issue by drd2aiki** [jontitmus-code/SuiteCRM8_docker#5]
Inside the Helper folder, the file says:

'/var/www/html/SuiteCRM/bin/console suitecrm:app:install -u "admin" -p "admin" -U "suitecrm" -P "suitecrm" -H "mysql_crm" -N "suitecrm" -S "http://localhost/" -d "yes"'

However, I think the correct command is located in the '/var/www/html/bin/' folder

**Comment by jontitmus-code** [comment]
@drd2aiki - that would depend on where you unpacked the ZIP file too...
The readme suggests that you unpack to `./www/SuiteCRM` making the helper file correct, if you unpack directly to `./www` then the command would be `/var/www/html/bin/console suitecrm:app:install -u "admin" -p "admin" -U "suitecrm" -P "suitecrm" -H "mysql_crm" -N "suitecrm" -S "http://localhost/" -d "yes"`

**Comment by drd2aiki** [comment]
Got it! Thanks!
